FROM microsoft/dotnet:latest

COPY . /app
WORKDIR /app

RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]

EXPOSE 60856/tcp
ENV ASPNETCORE_URLS http://*:60856
ENV ASPNETCORE_ENVIRONMENT Test

ENTRYPOINT ["dotnet", "run", "--server.urls", "http://*:60856"]